### ISSUE TITLE
Encoding error with Python 3.10

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/CENSO#25]
Seems like there is an issue with how encodings are handled in censo. This pops up with Python 3.10 on Windows:

```
(%PREFIX%) %SRC_DIR%>censo --help 
Traceback (most recent call last):
  File "C:\bld\censo_1644657234067\_test_env\Scripts\censo-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\bld\censo_1644657234067\_test_env\lib\site-packages\censo_qm\censo.py", line 36, in main
    args = cml(DESCR, internal_settings(), argv)
  File "C:\bld\censo_1644657234067\_test_env\lib\site-packages\censo_qm\inputhandling.py", line 1018, in cml
    args = parser.parse_args(argv)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 1825, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 2067, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 2007, in consume_optional
    take_action(action, args, option_string)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 1098, in __call__
    parser.print_help()
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 2555, in print_help
    self._print_message(self.format_help(), file)
  File "C:\bld\censo_1644657234067\_test_env\lib\argparse.py", line 2561, in _print_message
    file.write(message)
  File "C:\bld\censo_1644657234067\_test_env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0394' in position 6245: character maps to <undefined>
```

See https://www.python.org/dev/peps/pep-0597/

**Comment by fabothch** [comment]
I will have a look at it. 

But CENSO is designed to run with python >=3.6 and it has never been tested running on Windows. As long as xtb is not available on Windows this does not make sense anyway.
