### ISSUE TITLE
.censo2rc "evaluate_rrho = False" ignored in PART 2: Optimization

### ISSUE THREAD

**Issue by ph283804** [grimme-lab/CENSO#67]
For some unknown reason, am facing error in the bhess rrho part of xtb (it runs normally, but CENSO calls an error). Error is of the type "- WARNING  - CONF3 job recovery failed. Error: what went wrong in xtb_rrho. Check output files.".

If evaluate_rrho = True in .censo2rc, error happens during part 1, if .censo2rc instead has evaluate_rrho = False, part 1 runs normally but this keyword seems to be ignored in part 2 anyway. I can find no obvious error message in xtb_rrho or a reason for failure.

I have a zip file with the entire job, but am unsure how to share the file (github won't allow upload of larger than 25 MB).

**Comment by lmseidler** [comment]
Is it only the calculation of one conformer that fails? If yes, could you provide just the output file `xtb_rrho.out` of that specific conformer and also maybe the `xtb_rrho.coord`? Furthermore it could be helpful if you would rerun censo with `--loglevel DEBUG` and send also the `censo.log`.

Also please check out the newest commit of the code to see if this fixes the problem for you. I forgot to include the check for the rrho setting in part 2.

**Comment by ph283804** [comment]
It "fails" for all conformers (7 of them). I say "fails" because the rrho job itself returns no failure.

Will rerun the debug later and update this issue with the files/results.

**Comment by ph283804** [comment]
[censoerror.tar.gz](https://github.com/user-attachments/files/17778710/censoerror.tar.gz)

Apologies for the delay.

I uploaded three folders: one where T was set to 298.15 K and evaluate_rrho = true, one where 345.15 and false, and one where  345.15 and false and --loglevel DEBUG. 

All jobs were run on the same ensemble. 

when 345.15 K and evaluate_rrho = true, the error appears to happen in step 1 (screening) rather than step 2, so my guess is there are two errors here.

Apologies if this is confusing, please let me know if I can clarify anything

**Comment by lmseidler** [comment]
I can't find anything helpful here unfortunately. Did you try the newest commit? Because I found a bug in the version that you were using and fixed it there and I suspect that this caused the problems you're having.

**Comment by ph283804** [comment]
I just tested the current commit. It seems like the keyword is fixed for part 1, in part 2 I had the following error: 

Found constraints-file constraints.xtb ...
Optimization using macrocycles, 8 microcycles per step.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/__main__.py", line 4, in <module>
    entry_point()
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/cli/interface.py", line 55, in entry_point
    res, runtime = part.run(ensemble)
                   ^^^^^^^^^^^^^^^^^^
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/part.py", line 370, in run
    runtime = instance(**kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/utilities.py", line 428, in wrapper
    f(*args, **kwargs)
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/part.py", line 287, in wrapper
    return runner(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/ensembleopt/optimizer.py", line 92, in __call__
    self._optimize(cut=cut)
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/ensembleopt/optimization.py", line 115, in _optimize
    self.__macrocycle_opt(cut)
  File "/home/ph283804/anaconda3/lib/python3.12/site-packages/censo/ensembleopt/optimization.py", line 262, in __macrocycle_opt
    retry_failed=self.get_general_settings()["retry_failed"],
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'retry_failed'

**Comment by ph283804** [comment]
Additional context: Just ran a job with evaluate_rrho=true which has an identical input to a job which ran with no problems in version 2.1.0  (so somewhat unrelated to evaluate_rrho = false, apologies for repurposing the thread), error still came up, so seems to be a different bug entirely. 

Reproduced error with --loglevel DEBUG and uploaded .censo2rc, censo.runxtb.out, ensemble .xyz file, my constraints file and censo.log file in a zipped folder. The 2_OPTIMIZATION folder is still empty after the job crashes.

[debug.tar.gz](https://github.com/user-attachments/files/17842587/debug.tar.gz)

**Comment by lmseidler** [comment]
Apologies for the confusion, are you using the dev branch? Because this is not really intended, it is probably currently filled with bugs. You should use the main branch with the newest commit, that's what I meant.

**Comment by ph283804** [comment]
Hi, apologies for the confusion, I did think you meant the dev branch, changing to the main branch solved the issue
